modLoader = "javafml"
loaderVersion = "[52,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "piston_volume"
version = "${version}"
displayName = "Dynamic Piston Volume"
authors = "Adi"
description = '''
Makes the piston volume dependent on how many blocks get pushed
'''
#logoFile = ""

[[dependencies.piston_volume]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.piston_volume]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"